var TREE_ITEMS = [
	['Home','index.html',{'sb':' '},
		['Introduction', 'Introduction.html',{'tt':'Introduction','sb':'Introduction.html'},
			['Background', 'Background.html',{'tt':'Background','sb':'Background.html'},],
			['What is Activity Data?', 'What_is_Activity_Data.html',{'tt':'What is Activity Data?','sb':'What_is_Activity_Data.html'},],
			['Why should you care?', 'Why_should_you_care.html',{'tt':'Why should you care?','sb':'Why_should_you_care.html'},],
			['What are the particular benefits of Activity Data?', 'benefits_of_Activity_Data.html',{'tt':'What are the particular benefits of Activity Data?','sb':'benefits_of_Activity_Data.html'},],
			['What is Activity Data useful for?', 'useful_for.html',{'tt':'What is Activity Data useful for?','sb':'useful_for.html'},],
],
		['Benefits of using activity data', 'Benefits.html',{'tt':'Benefits of using activity data','sb':'Benefits.html'},
			['Supporting student success', 'Student_success.html',{'tt':'Supporting student success','sb':'Student_success.html'},
				['Benefits of AEIOU ', 'SSS-Benefits-AEIOU.html',{'tt':'Benefits of Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'SSS-Benefits-AEIOU.html'},],
				['Benefits of LIDP', 'SSS-Benefits-LIDP.html',{'tt':'Benefits of Library Impact Data Project (LIDP)','sb':'SSS-Benefits-LIDP.html'},],
				['Benefits of RISE ', 'SSS-Benefits-RISE.html',{'tt':'Benefits of Recommendations Improve the Search Experience (RISE)','sb':'SSS-Benefits-RISE.html'},],
				['Benefits of STAR- Trak', 'SSS-_Benefits-STAR-Trak_NG.html',{'tt':'Benefits of STAR- Trak: NG','sb':'SSS-_Benefits-STAR-Trak_NG.html'},],
],
			['Service and system improvement', 'Service_and_system_improvement.html',{'tt':'Service and system improvement','sb':'Service_and_system_improvement.html'},
				['Benefits of AEIOU', 'Benefits-SSI-AEIOU.html',{'tt':'Benefits of Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'Benefits-SSI-AEIOU.html'},],
				['Benefits of AGtivity', 'Benefits-SSI-AGtivity.html',{'tt':'Benefits of Exploiting Access Grid Activity Data (AGtivity)','sb':'Benefits-SSI-AGtivity.html'},
					['Case Study 1: A Tale of Two Rooms', 'AGtivity_Case_Study_1.html',{'tt':'Case Study 1: A Tale of Two Rooms','sb':'AGtivity_Case_Study_1.html'},],
					['Case Study 2: Testing\, testing\, testing', 'AGtivity_Case_Study_2.html',{'tt':'Case Study 2: Testing\, testing\, testing','sb':'AGtivity_Case_Study_2.html'},],
					['Case Study 3: To Book or Not To Book', 'AGtivity_Case_Study_3.html',{'tt':'Case Study 3: To Book or Not To Book','sb':'AGtivity_Case_Study_3.html'},],
					['Case Study 4: CO2 - loads of it', 'AGtivity_Case_Study_4.html',{'tt':'Case Study 4: CO2 - loads of it','sb':'AGtivity_Case_Study_4.html'},],
],
				['Benefits of SALT', 'Benefits-SSI-SALT.html',{'tt':'Benefits of Surfacing of the Long Academic Tale (SALT)','sb':'Benefits-SSI-SALT.html'},],
],
],
		['Lessons learnt', 'Lessons_learnt.html',{'tt':'Lessons learnt','sb':'Lessons_learnt.html'},
			['Legal: AEIOU ', 'LL_legal_AEIOU.html',{'tt':'Legal: Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'LL_legal_AEIOU.html'},],
			['Legal: LIDP', 'LL_legal_LIDP.html',{'tt':'Legal: Library Impact Data Project (LIDP)','sb':'LL_legal_LIDP.html'},],
			['Legal: STAR-Trak', 'LL_legal_STAR-Trak.html',{'tt':'Legal: Student Tracking And Retention (Next Generation): STAR-Trak: NG','sb':'LL_legal_STAR-Trak.html'},],
			['Data: AEIOU ', 'LL_data_AEIOU.html',{'tt':'Data: Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'LL_data_AEIOU.html'},],
			['Data: LIDP', 'LL_data_LIDP.html',{'tt':'Data: Library Impact Data Project (LIDP)','sb':'LL_data_LIDP.html'},],
			['OpenURL', 'LL_data_OpenURL.html',{'tt':'Using OpenURL Activity Data','sb':'LL_data_OpenURL.html'},],
			['Data: RISE', 'LL_data_RISE.html',{'tt':'Data: Recommendations Improve the Search Experience (RISE)','sb':'LL_data_RISE.html'},],
			['Data: SALT', 'LL_data_SALT.html',{'tt':'Data: Surfacing the Academic Long Tail (SALT)','sb':'LL_data_SALT.html'},],
			['Data: STAR-Trak', 'LL_data_STAR-Trak.html',{'tt':'Data: Student Tracking And Retention (Next Generation): STAR-Trak: NG','sb':'LL_data_STAR-Trak.html'},],
			['Recommender systems: AEIOU', 'LL_recommend_AEIOU.html',{'tt':'Recommender systems: Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'LL_recommend_AEIOU.html'},],
			['Recommender systems: RISE', 'LL_recommend_RISE.html',{'tt':'Recommender systems: Recommendations Improve the Search Experience (RISE)','sb':'LL_recommend_RISE.html'},],
			['Recommender systems: SALT', 'LL_recommend_SALT.html',{'tt':'Recommender systems: Surfacing the Academic Long Tail (SALT)','sb':'LL_recommend_SALT.html'},],
],
		['High level guidance', 'Guides.html',{'tt':'High level guidance','sb':'Guides.html'},
			['Building a business case', 'Building_a_business_case_guide.html',{'tt':'Building a business case','sb':'Building_a_business_case_guide.html'},
				['Guidance on creating a business case', 'Guidance_on_creating_a_business_case.html',{'tt':'Guidance on creating a business case','sb':'Guidance_on_creating_a_business_case.html'},],
],
			['Sharing activity data: Legal issues', 'Guide_legal.html',{'tt':'Sharing activity data: Legal issues','sb':'Guide_legal.html'},],
			['Informing users about data collection', 'Informing_users_about_data_collection_gu.html',{'tt':'Informing users about data collection','sb':'Informing_users_about_data_collection_gu.html'},],
			['Which events are significant?', 'Which_events_are_significant_.html',{'tt':'Which events are significant?','sb':'Which_events_are_significant_.html'},],
			['Identifying library data sources', 'Library_data_sources_guide.html',{'tt':'Identifying library data sources','sb':'Library_data_sources_guide.html'},],
			['What’s behind a recommendation?', 'Whats_behind_a_recommendation.html',{'tt':'What’s behind a recommendation?','sb':'Whats_behind_a_recommendation.html'},],
			['Strategies for collecting and storing activity dat... ', 'Data_strategies__guide.html',{'tt':'Strategies for collecting and storing activity data','sb':'Data_strategies__guide.html'},],
			['Anonymising data', 'Anonymisation_guide.html',{'tt':'Anonymising data','sb':'Anonymisation_guide.html'},],
			['Bringing activity data to life', 'Visualisation_guide.html',{'tt':'Bringing activity data to life','sb':'Visualisation_guide.html'},],
			['Enabling student success', 'Student_success_guide.html',{'tt':'Enabling student success','sb':'Student_success_guide.html'},],
],
		['Data protection issues', 'Data_protection_issues.html',{'tt':'Data protection issues','sb':'Data_protection_issues.html'},
			['Consent management', 'Consent_management.html',{'tt':'Consent management','sb':'Consent_management.html'},],
			['AEIOU', 'DP_AEIOU.html',{'tt':'Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'DP_AEIOU.html'},],
			['EVAD', 'DP_EVAD.html',{'tt':'Exposing VLE data (EVAD)','sb':'DP_EVAD.html'},],
			['OpenURL ', 'DP_OpenURL.html',{'tt':'Using OpenURL Activity Data','sb':'DP_OpenURL.html'},],
			['RISE', 'DP_RISE.html',{'tt':'Recommendations Improve the Search Experience (RISE)','sb':'DP_RISE.html'},],
			['STAR-Trak', 'dataprotection_STAR-Trak.html',{'tt':'Student Tracking And Retention: STAR-Trak: NG','sb':'dataprotection_STAR-Trak.html'},],
],
		['Licensing and sharing activity data', 'Licensing_and_sharing_activity_data.html',{'tt':'Licensing and sharing activity data','sb':'Licensing_and_sharing_activity_data.html'},
			['Licensing of data', 'Licensing_of_data.html',{'tt':'Licensing of data','sb':'Licensing_of_data.html'},
				['Licensing Considerations', 'Licensing_Considerations.html',{'tt':'Licensing Considerations','sb':'Licensing_Considerations.html'},],
				['Licenses used', 'Licenses_used.html',{'tt':'Licenses used','sb':'Licenses_used.html'},
					['AEIOU', 'Licensing_AEIOU.html',{'tt':'Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'Licensing_AEIOU.html'},],
					['AGtivity', 'Licensing_AGtivity.html',{'tt':'Exploiting Access Grid Activity Data (AGtivity)','sb':'Licensing_AGtivity.html'},],
					['EVAD', 'Licensing_EVAD.html',{'tt':'Exposing VLE activity data (EVAD)','sb':'Licensing_EVAD.html'},],
					['RISE', 'Licensing_RISE.html',{'tt':'Recommendations Improve the Search Experience (RISE)','sb':'Licensing_RISE.html'},],
					['SALT', 'Licensing_SALT.html',{'tt':'Surfacing the Academic Long Tail (SALT)','sb':'Licensing_SALT.html'},],
					['STAR-Trak', 'Licensing_STAR-Trak.html',{'tt':'Student Tracking And Retention: STAR-Trak: NG','sb':'Licensing_STAR-Trak.html'},],
					['UCIAD', 'Licensing_UCIAD.html',{'tt':'User-Centric Integration of Activity Data (UCIAD)','sb':'Licensing_UCIAD.html'},],
],
],
			['Publishing (anonymisation and sharing)', 'Publishing.html',{'tt':'Publishing (anonymisation and sharing)','sb':'Publishing.html'},
				['Data Sharing Advice from the Information Commissioner\'s Office', 'Data_Sharing_Advice_from_the_ICO.html',{'tt':'Data Sharing Advice from the Information Commissioner\'s Office','sb':'Data_Sharing_Advice_from_the_ICO.html'},],
				['AEIOU', 'Publish_AEIOU.html',{'tt':'Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'Publish_AEIOU.html'},],
				['AGtivity', 'Publish_AGtivity.html',{'tt':'Exploiting Access Grid Activity Data (AGtivity)','sb':'Publish_AGtivity.html'},],
				['EVAD', 'Publish_EVAD.html',{'tt':'Exposing VLE activity data (EVAD)','sb':'Publish_EVAD.html'},],
				['LIDP', 'Publish_LIDP.html',{'tt':'Library Impact Data Project (LIDP)','sb':'Publish_LIDP.html'},],
				['OpenURL', 'Publish_OpenURL.html',{'tt':'Using OpenURL Activity Data','sb':'Publish_OpenURL.html'},],
				['RISE', 'Publish_RISE.html',{'tt':'Recommendations Improve the Search Experience (RISE)','sb':'Publish_RISE.html'},],
				['SALT', 'Publish_SALT.html',{'tt':'Surfacing the Academic Long Tail (SALT)','sb':'Publish_SALT.html'},],
				['MOSAIC', 'Publish_MOSAIC.html',{'tt':'MOSAIC','sb':'Publish_MOSAIC.html'},],
				['Sharing data', 'Sharing_data.html',{'tt':'Sharing data','sb':'Sharing_data.html'},],
],
],
		['Collecting\, processing and presenting activity dat... ', 'Computation.html',{'tt':'Collecting\, processing and presenting activity data','sb':'Computation.html'},
			['Collecting', 'Collecting.html',{'tt':'Collecting','sb':'Collecting.html'},
				['The data to collect', 'What_data.html',{'tt':'The data to collect','sb':'What_data.html'},
					['LIDP', 'Collecting_LIDP.html',{'tt':'LIDP','sb':'Collecting_LIDP.html'},],
],
				['Data quality and completeness', 'Data_quality_and_completeness.html',{'tt':'Data quality and completeness','sb':'Data_quality_and_completeness.html'},
					['AGtivity', 'Collecting-AGtivity.html',{'tt':'Exploiting Access Grid Activity Data (AGtivity)','sb':'Collecting-AGtivity.html'},],
					['EVAD', 'Collecting-EVAD.html',{'tt':'Exposing VLE data (EVAD)','sb':'Collecting-EVAD.html'},],
					['LIDP', 'Collecting-LIDP.html',{'tt':'Library Impact Data Project (LIDP)','sb':'Collecting-LIDP.html'},],
],
				['Data formats', 'Data_formats.html',{'tt':'Data formats','sb':'Data_formats.html'},
					['AEIOU', 'Collecting-AEIOU.html',{'tt':'AEIOU','sb':'Collecting-AEIOU.html'},],
],
				['Data collection tools', 'Data_collection_tools.html',{'tt':'Data collection tools','sb':'Data_collection_tools.html'},],
],
			['Processing', 'Processing.html',{'tt':'Processing','sb':'Processing.html'},
				['Aggregation of multiple data sets', 'Aggregation.html',{'tt':'Aggregation of multiple data sets','sb':'Aggregation.html'},],
				['Filtering data sets', 'Filtering.html',{'tt':'Filtering data sets','sb':'Filtering.html'},],
				['Recommendation algorithms', 'Recommendation_algorithms.html',{'tt':'Recommendation algorithms','sb':'Recommendation_algorithms.html'},
					['AEIOU', 'Processing_AEIOU.html',{'tt':'Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'Processing_AEIOU.html'},],
					['LIDP', 'Processing_LIDP.html',{'tt':'Library Impact Data Project (LIDP)','sb':'Processing_LIDP.html'},],
					['RISE', 'Processing_RISE.html',{'tt':'Recommendations Improve the Search Experience (RISE)','sb':'Processing_RISE.html'},],
],
				['Learning analytics', 'Learning_analytics.html',{'tt':'Learning analytics','sb':'Learning_analytics.html'},],
				['Further analysis', 'Analysis.html',{'tt':'Further analysis','sb':'Analysis.html'},],
],
			['Presentation', 'Presentation.html',{'tt':'Presentation','sb':'Presentation.html'},
				['visualisation', 'Presentation-visualisation.html',{'tt':'visualisation','sb':'Presentation-visualisation.html'},
					['AGtivity', 'Visualisation-AGtivity.html',{'tt':'Exploiting Access Grid Activity Data (AGtivity)','sb':'Visualisation-AGtivity.html'},],
					['EVAD', 'Visualisation_EVAD.html',{'tt':'Exposing VLE activity data (EVAD)','sb':'Visualisation_EVAD.html'},],
					['LIDP', 'Visualisation-LIDP.html',{'tt':'Library Impact Data Project (LIDP)','sb':'Visualisation-LIDP.html'},],
					['OpenURL', 'Visualisation_OpenURL.html',{'tt':'Using OpenURL Activity Data','sb':'Visualisation_OpenURL.html'},],
],
				['User interface for recommender systems', 'Presentation-User_interface.html',{'tt':'User interface for recommender systems','sb':'Presentation-User_interface.html'},
					['RISE', 'Visualisation-RISE.html',{'tt':'Recommendations Improve the Search Experience (RISE)','sb':'Visualisation-RISE.html'},],
],
],
],
		['Related work', 'Related_work.html',{'tt':'Related work','sb':'Related_work.html'},
			['Related JISC funded programmes and projects', 'Other_JISC.html',{'tt':'Related JISC funded programmes and projects','sb':'Other_JISC.html'},],
			['International', 'Other_International.html',{'tt':'International','sb':'Other_International.html'},
				['Collaborative partners', 'Collaborative_partners.html',{'tt':'Collaborative partners','sb':'Collaborative_partners.html'},],
				['Prior developments', 'Prior_developments.html',{'tt':'Prior developments','sb':'Prior_developments.html'},],
				['Academic analytics resources from Educause', 'Educause.html',{'tt':'Academic analytics resources from Educause','sb':'Educause.html'},],
				['Other Publications and Online Resources', 'Other_Publications.html',{'tt':'Other Publications and Online Resources','sb':'Other_Publications.html'},],
],
],
		['The JISC activity data projects', 'Projects.html',{'tt':'The JISC activity data projects','sb':'Projects.html'},
			['Activity data to Enhance and Increase Open-access Usage (AEIOU)', 'AEIOU.html',{'tt':'Activity data to Enhance and Increase Open-access Usage (AEIOU)','sb':'AEIOU.html'},],
			['Exploiting Access Grid Activity Data (AGtivity)', 'AGtivity.html',{'tt':'Exploiting Access Grid Activity Data (AGtivity)','sb':'AGtivity.html'},
				['Technologies and Standards', 'Agtivity_Technologies_and_Standards.html',{'tt':'AGtivity: Technologies and Standards','sb':'Agtivity_Technologies_and_Standards.html'},],
				['Wins and fails', 'Agtivity_Wins_and_fails.html',{'tt':'AGtivity: Wins and fails','sb':'Agtivity_Wins_and_fails.html'},],
				['Numbers', 'Agtivity_Numbers.html',{'tt':'AGtivity: Numbers','sb':'Agtivity_Numbers.html'},],
				['Next steps', 'AGtivity_next_steps.html',{'tt':'AGtivity: next steps','sb':'AGtivity_next_steps.html'},],
],
			['Exposing VLE activity data (EVAD)', 'Exposing_VLE_data.html',{'tt':'Exposing VLE activity data (EVAD)','sb':'Exposing_VLE_data.html'},],
			['Library Impact Data Project (LIDP)', 'LIDP.html',{'tt':'Library Impact Data Project (LIDP)','sb':'LIDP.html'},
				['Thoughts on the hypothesis', 'LIDP_Thoughts_on_the_hypothesis.html',{'tt':'LIDP: Thoughts on the hypothesis','sb':'LIDP_Thoughts_on_the_hypothesis.html'},],
				['Implications of the evidence', 'LIDP_Implications_of_the_evidence.html',{'tt':'LIDP: Implications of the evidence','sb':'LIDP_Implications_of_the_evidence.html'},],
				['Articles and conference papers', 'LIDP_Articles_and_conference_papers.html',{'tt':'LIDP: Articles and conference papers','sb':'LIDP_Articles_and_conference_papers.html'},],
				['Next steps', 'LIDP_Next_steps.html',{'tt':'LIDP: Next steps','sb':'LIDP_Next_steps.html'},],
],
			['Recommendations Improve the Search Experience (RISE) ', 'RISE.html',{'tt':'Recommendations Improve the Search Experience (RISE)','sb':'RISE.html'},
				['How do we plan to evaluate the hypothesis?', 'RISE_How_to_evaluate_the_hypothesis.html',{'tt':'RISE: How do we plan to evaluate the hypothesis?','sb':'RISE_How_to_evaluate_the_hypothesis.html'},],
				['Next steps', 'RISE_Next_steps.html',{'tt':'RISE: Next steps','sb':'RISE_Next_steps.html'},],
],
			['Surfacing the Academic Long Tail (SALT)', 'SALT.html',{'tt':'Surfacing the Academic Long Tail (SALT)','sb':'SALT.html'},
				['Evaluation', 'SALT_Evaluation.html',{'tt':'SALT: Evaluation','sb':'SALT_Evaluation.html'},],
				['next steps', 'SALT_next_steps.html',{'tt':'SALT: next steps','sb':'SALT_next_steps.html'},],
],
			['Student Tracking And Retention: Next Generation (STAR-Trak) ', 'STAR-Trak.html',{'tt':'Student Tracking And Retention (Next Generation): STAR-Trak: NG','sb':'STAR-Trak.html'},
				['System description', 'STAR-Trak__NG-description.html',{'tt':'STAR-Trak: NG','sb':'STAR-Trak__NG-description.html'},],
				['Next steps', 'STAR-Trak-Further_work.html',{'tt':'STAR-Trak: NG next steps','sb':'STAR-Trak-Further_work.html'},],
],
			['User-Centric Integration of Activity Data (UCIAD)', 'UCIAD.html',{'tt':'User-Centric Integration of Activity Data (UCIAD)','sb':'UCIAD.html'},
				['Hypotheses', 'UCIAD-Hypotheses.html',{'tt':'UCIAD: Hypotheses','sb':'UCIAD-Hypotheses.html'},],
				['Using\, refining\, customising and reusing on... ', 'UCIAD-Using-ontologies.html',{'tt':'UCIAD: Using\, refining\, customising and reusing ontologies','sb':'UCIAD-Using-ontologies.html'},],
				['Next steps', 'UCIAD_next_steps.html',{'tt':'UCIAD: next steps','sb':'UCIAD_next_steps.html'},],
],
			['Using OpenURL Activity Data', 'OpenURL.html',{'tt':'Using OpenURL Activity Data','sb':'OpenURL.html'},
				['Next steps', 'OpenURL_next_steps.html',{'tt':'OpenURL: next steps','sb':'OpenURL_next_steps.html'},],
],
],
		['Technical recipes', 'Recipes.html',{'tt':'Technical recipes','sb':'Recipes.html'},
			['Extracting data', 'Extracting_data.html',{'tt':'Extracting data','sb':'Extracting_data.html'},
				['Extract authentication counts from the EZproxy Authentication and Access Software', 'Extract_authentication_counts_from_EZpro.html',{'tt':'Extract authentication counts from the EZproxy Authentication and Access Software','sb':'Extract_authentication_counts_from_EZpro.html'},],
				['Extract circulation data from the Horizon Library Management System', 'LIDP_R_2.html',{'tt':'Extract circulation data from the Horizon Library Management System','sb':'LIDP_R_2.html'},],
				['Extract entry statistics from the Sentry library gate entry system', 'LIDP_R_4.html',{'tt':'Extract entry statistics from the Sentry library gate entry system','sb':'LIDP_R_4.html'},],
				['Extract user ID and course code from CIRCE MI', 'Extract_from_CIRCE_MI.html',{'tt':'Extract user ID and course code from CIRCE MI','sb':'Extract_from_CIRCE_MI.html'},],
				['Extract anonymised loan data from Talis Alto', 'Recipe_SALT_extract__Talis.html',{'tt':'Extract anonymised loan data from Talis Alto','sb':'Recipe_SALT_extract__Talis.html'},],
				['Extract trace data from log files', 'Extract_trace_data_from_log_files.html',{'tt':'Extract trace data from log files','sb':'Extract_trace_data_from_log_files.html'},],
],
			['Processing data', 'Processing_data.html',{'tt':'Processing data','sb':'Processing_data.html'},
				['Stitching together library data with Excel', 'Recipe_Stitching_together_library_data_w.html',{'tt':'Stitching together library data with Excel','sb':'Recipe_Stitching_together_library_data_w.html'},],
				['Preparing attention data for processing by SPSS', 'LIDP_R_3.html',{'tt':'Preparing attention data for processing by SPSS','sb':'LIDP_R_3.html'},],
				['Manipulating activity data using Linux commands', 'Playing_With_Largeish_CSV_Files.html',{'tt':'Manipulating activity data using Linux commands','sb':'Playing_With_Largeish_CSV_Files.html'},],
				['Manipulating activity data using Ruby', 'Playing_with_OpenURL_Router_Data_in_Ruby.html',{'tt':'Manipulating activity data using Ruby','sb':'Playing_with_OpenURL_Router_Data_in_Ruby.html'},],
				['Provide course based recommendations', 'Provide_course_based_recommendations.html',{'tt':'Provide course based recommendations','sb':'Provide_course_based_recommendations.html'},],
				['Process EZProxy log', 'Process_EZProxy_log.html',{'tt':'Process EZProxy log','sb':'Process_EZProxy_log.html'},],
				['Provide relationship based recommendations', 'relationship_based_recommendations.html',{'tt':'Provide relationship based recommendations','sb':'relationship_based_recommendations.html'},],
				['Search term based recommendations', 'Search_term_recommendations.html',{'tt':'Search term based recommendations','sb':'Search_term_recommendations.html'},],
				['How to Pivot data in Open Office Spreadsheet', 'How_to_Pivot_data_in_Open_Office_Spreads.html',{'tt':'How to Pivot data in Open Office Spreadsheet','sb':'How_to_Pivot_data_in_Open_Office_Spreads.html'},],
				['Exploitable artefact: UCIAD Ontology', 'Exploitable_artefact__UCIAD_Ontology.html',{'tt':'Exploitable artefact: UCIAD Ontology','sb':'Exploitable_artefact__UCIAD_Ontology.html'},],
],
			['Presenting data', 'Presenting_data.html',{'tt':'Presenting data','sb':'Presenting_data.html'},
				['Producing PDF Reports Programmatically', 'Producing_PDF_Reports_Programmatically.html',{'tt':'Producing PDF Reports Programmatically','sb':'Producing_PDF_Reports_Programmatically.html'},],
				['Plotting Calendar Data with GNUplot', 'Plotting_Calendar_Data_with_GNUplot.html',{'tt':'Plotting Calendar Data with GNUplot','sb':'Plotting_Calendar_Data_with_GNUplot.html'},],
				['How to work with Gephi to visualise a network of Sites connected by Users', 'Recipe_Gephi.html',{'tt':'How to work with Gephi to visualise a network of Sites connected by Users ','sb':'Recipe_Gephi.html'},],
				['Visualising OpenURL Referrals Using Gource', 'Visualising_OpenURL_Referrals_Using_Gour.html',{'tt':'Visualising OpenURL Referrals Using Gource','sb':'Visualising_OpenURL_Referrals_Using_Gour.html'},],
				['OpenURL Router Data: Total Requests by Date', 'Visualising_OpenURL_Total_Requests_by_Da.html',{'tt':'OpenURL Router Data: Total Requests by Date','sb':'Visualising_OpenURL_Total_Requests_by_Da.html'},],
],
			['Other', 'Other_recipes.html',{'tt':'Other','sb':'Other_recipes.html'},],
],
		['Synthesis method', 'Synthesismethod.html',{'tt':'Synthesis method','sb':'Synthesismethod.html'},],
		['Recommendations for further work', 'Recommendations.html',{'tt':'Recommendations for further work','sb':'Recommendations.html'},
			['Student success', 'Recommendation_Student_success.html',{'tt':'Student success','sb':'Recommendation_Student_success.html'},],
			['User experience', 'Recommendation_User_experience.html',{'tt':'User experience','sb':'Recommendation_User_experience.html'},],
			['Service and system improvement', 'Recommendation_Service_and_system_improv.html',{'tt':'Service and system improvement','sb':'Recommendation_Service_and_system_improv.html'},],
			['Other', 'Recommendation_Other.html',{'tt':'Other','sb':'Recommendation_Other.html'},],
],
		['Acknowledgements', 'Acknowledgements.html',{'tt':'Acknowledgements','sb':'Acknowledgements.html'},],

]
];